steps:
  # Install dependencies
  - name: 'node:18'
    entrypoint: npm
    args: ['ci']
    timeout: '300s'

  # Build the application
  - name: 'node:18'
    entrypoint: npm
    args: ['run', 'build']
    env:
      - 'NODE_ENV=production'
      - 'VITE_GOOGLE_CLIENT_ID=${_VITE_GOOGLE_CLIENT_ID}'
      - 'VITE_GOOGLE_PROJECT_ID=${_VITE_GOOGLE_PROJECT_ID}'
      - 'VITE_GOOGLE_AUTH_URI=${_VITE_GOOGLE_AUTH_URI}'
      - 'VITE_GOOGLE_TOKEN_URI=${_VITE_GOOGLE_TOKEN_URI}'
      - 'VITE_GOOGLE_AUTH_PROVIDER_CERT_URL=${_VITE_GOOGLE_AUTH_PROVIDER_CERT_URL}'
      - 'VITE_GOOGLE_CLIENT_SECRET=${_VITE_GOOGLE_CLIENT_SECRET}'
      - 'VITE_GOOGLE_DRIVE_FOLDER_ID=${_VITE_GOOGLE_DRIVE_FOLDER_ID}'
    timeout: '300s'

  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'us-east4-docker.pkg.dev/${PROJECT_ID}/abstract-secure/app', 
           '.']
    timeout: '600s'

  # Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'us-east4-docker.pkg.dev/${PROJECT_ID}/abstract-secure/app']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['run', 'deploy', 'abstract-secure',
           '--image', 'us-east4-docker.pkg.dev/${PROJECT_ID}/abstract-secure/app',
           '--region', 'us-east4',
           '--platform', 'managed',
           '--allow-unauthenticated']
    timeout: '300s'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-east4'

# Store artifacts
artifacts:
  objects:
    location: 'gs://${PROJECT_ID}_cloudbuild/abstract-secure/'
    paths: ['dist/**']

# Configure timeout
timeout: '1200s'

# Use high-CPU machine
options:
  machineType: 'E2_HIGHCPU_8'
