steps:
  # Install dependencies
  - name: 'node:18'
    id: 'install'
    entrypoint: npm
    args: ['ci']
    env:
      - 'NODE_ENV=production'
    waitFor: ['-']  # Start immediately

  # Build the application
  - name: 'node:18'
    id: 'build'
    entrypoint: npm
    args: ['run', 'build']
    env:
      - 'NODE_ENV=production'
      - 'VITE_GOOGLE_CLIENT_ID=${_VITE_GOOGLE_CLIENT_ID}'
      - 'VITE_GOOGLE_PROJECT_ID=${_VITE_GOOGLE_PROJECT_ID}'
      - 'VITE_GOOGLE_AUTH_URI=${_VITE_GOOGLE_AUTH_URI}'
      - 'VITE_GOOGLE_TOKEN_URI=${_VITE_GOOGLE_TOKEN_URI}'
      - 'VITE_GOOGLE_AUTH_PROVIDER_CERT_URL=${_VITE_GOOGLE_AUTH_PROVIDER_CERT_URL}'
      - 'VITE_GOOGLE_CLIENT_SECRET=${_VITE_GOOGLE_CLIENT_SECRET}'
      - 'VITE_GOOGLE_DRIVE_FOLDER_ID=${_VITE_GOOGLE_DRIVE_FOLDER_ID}'
    waitFor: ['install']

  # Build the container
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-build'
    args: 
      - 'build'
      - '--network=cloudbuild'
      - '-t'
      - 'gcr.io/$PROJECT_ID/abstract-secure'
      - '.'
    waitFor: ['build']

  # Push the container
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-push'
    args: ['push', 'gcr.io/$PROJECT_ID/abstract-secure']
    waitFor: ['docker-build']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'abstract-secure'
      - '--image'
      - 'gcr.io/$PROJECT_ID/abstract-secure'
      - '--region'
      - 'us-east4'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
    waitFor: ['docker-push']

# Configure timeout and logging
timeout: '1800s'
queueTtl: '3600s'
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: '100'
  dynamicSubstitutions: true
  env:
    - 'DOCKER_BUILDKIT=1'
  volumes:
    - name: 'npm-cache'
      path: '/root/.npm'

# Define the images to be pushed
images:
  - 'gcr.io/$PROJECT_ID/abstract-secure'

# Add tags for better organization
tags: ['abstract-secure', 'production-deploy']

# Configure artifacts storage
artifacts:
  objects:
    location: 'gs://$PROJECT_ID-builds/'
    paths: ['dist/**']
